server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbhibernaterestapi
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "UlmUlsZrJP4vDEeq1WvxFec0wlZSQP8mB2CpN1pyhK4gDLI3x9zkCSly2YANDp/X"